theme: jekyll-theme-leap-day
title: Welcome to the GitHub page of Elian Griffioen
description: I'm Elian Griffioen, student Methodology & Statistics and publish my scientific (and some non-scientific fun) work on this page
