theme: jekyll-theme-architect
title: Welcome to the GitHub page of Elian Griffioen
description: I'm Elian Griffioen, student Methodlogy & Statistics and publish my scientific (and some non-scientific fun) work on this page
